# Generated by Django 3.1.6 on 2021-03-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_auto_20210308_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to='recipe_app.RecipeItem'),
        ),
    ]
